export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Thomas Shelby",
    },
    {
        id: 2,
        profilePicture: "assets/person/p2.png",
        username: "Suresh Doe",
    },
    {
        id: 3,
        profilePicture: "assets/person/p3.png",
        username: "Sara Devis",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpg",
        username: "Dora Hawks",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Rajib Holden",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Soham Bennett",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Kristen Thomas",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpg",
        username: "Abhra Duty",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.webp",
        username: "Safak Kocaoglu",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Europe pushes travel that’s climate friendly.",
        photo: "assets/post/1.webp",
        date: "3 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.webp",
        date: "10 mins ago",
        userId: 2,
        like: 5,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "assets/post/3.webp",
        date: "1 hour ago",
        userId: 3,
        like: 81,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.webp",
        date: "3 hours ago",
        userId: 4,
        like: 5,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/post/5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 21,
        comment: 5,
    },
    {
        id: 6,
        photo: "assets/post/6.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "The Best European Christmas Markets To Visit This Winter.",
        photo: "assets/post/7.webp",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "assets/post/8.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "The traditional craft of polished metal mirror of Aranmula in Kerala.",
        photo: "assets/post/9.webp",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "assets/post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];